### ISSUE TITLE
invalid module name

### ISSUE THREAD

**Issue by DemonBigj781** [ldtteam/Piston-Unlimited#25]
05:47:04.636
launcher
main
Version does not support log configuration, will assume one plaintext entry per line
05:47:06.541
game
2022-12-01 05:47:06,524 main WARN Advanced terminal features are not available in this environment
05:47:06.678
game
[05:47:06] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, DemonBigj781, --version, forge-43.1.65, --gameDir, C:\Users\Owner\curseforge\minecraft\Instances\minecollonies, --assetsDir, C:\Users\Owner\curseforge\minecraft\Install\assets, --assetIndex, 1.19, --uuid, 50af93fba56041b69d256e24fcec87db, --accessToken, ????????, --clientId, OWU0YjNhNDMtMWQ0Yy00ZjI4LTgwMGItY2M2YmM3ZWQ1MWFh, --xuid, 2533275024964474, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 43.1.65, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
05:47:06.681
game
[05:47:06] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0
05:47:07.124
game
Exception in thread "main" java.lang.IllegalArgumentException: multi-piston: Invalid module name: 'multi-piston' is not a Java identifier
05:47:07.124
game
at java.base/jdk.internal.module.Checks.requireModuleName(Checks.java:59)
05:47:07.124
game
at java.base/java.lang.module.ModuleDescriptor$Builder.<init>(ModuleDescriptor.java:1515)
05:47:07.124
game
at java.base/java.lang.module.ModuleDescriptor.newAutomaticModule(ModuleDescriptor.java:2395)
05:47:07.124
game
at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.SimpleJarMetadata.descriptor(SimpleJarMetadata.java:13)
05:47:07.124
game
at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.computeDescriptor(Jar.java:51)
05:47:07.124
game
at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar$JarModuleDataProvider.descriptor(Jar.java:276)
05:47:07.124
game
at MC-BOOTSTRAP/fmlloader@1.19.2-43.1.65/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.visitFile(ModDirTransformerDiscoverer.java:62)
05:47:07.124
game
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
05:47:07.124
game
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
05:47:07.124
game
at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
05:47:07.124
game
at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
05:47:07.124
game
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
05:47:07.124
game
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
05:47:07.124
game
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
05:47:07.124
game
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
05:47:07.124
game
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
05:47:07.124
game
at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
05:47:07.124
game
at MC-BOOTSTRAP/fmlloader@1.19.2-43.1.65/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.scan(ModDirTransformerDiscoverer.java:50)
05:47:07.125
game
at MC-BOOTSTRAP/fmlloader@1.19.2-43.1.65/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.candidates(ModDirTransformerDiscoverer.java:33)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.serviceapi.ITransformerDiscoveryService.candidates(ITransformerDiscoveryService.java:48)
05:47:07.125
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.lambda$discoverServices$14(TransformationServicesHandler.java:125)
05:47:07.125
game
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
05:47:07.125
game
at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
05:47:07.125
game
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
05:47:07.125
game
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
05:47:07.125
game
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
05:47:07.125
game
at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
05:47:07.125
game
at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
05:47:07.125
game
at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
05:47:07.125
game
at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
05:47:07.125
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:127)
05:47:07.125
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:86)
05:47:07.125
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
05:47:07.125
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
05:47:07.125
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
05:47:07.125
game
at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

that is the whole crash log. it just crashes

**Comment by toadie-odie** [comment]
I get the same crash on Forge version 43.1.65 but not on 43.1.7 - but I need 43.1.65 due to compatibility issues other mods have with 43.1.7.

**Comment by OcWebb** [comment]
Getting the same issue here on Forge 1.19.2 - 43.1.65

**Comment by Raycoms** [comment]
fixed here https://www.curseforge.com/minecraft/mc-mods/multi-piston/files
